# Cat this file to /etc/nginx/sites-available/st.test
# ln -s
server {

        listen 80;
        listen [::]:80;

        server_name st.test;
        index index.php;
        root /var/www/st.test/www/public;

        client_max_body_size 100M;

        location ~ ^(\.ht|.gitignore) {
                deny all;
            }

        location ~ ^/(\.git|\.github)/ {
            deny all;
        }

        location ~ ^/(build|images)/ {
                expires 1h;
                add_header Cache-Control "public, must-revalidate";
                access_log off;
        }

        location / {
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://127.0.0.1:12201;
        }

        access_log /var/log/nginx/st.test.access.log combined;
        error_log  /var/log/nginx/st.test.error.log;
}